### ISSUE TITLE
Add cache buster to http requests 

### ISSUE THREAD

**Issue by brendancol** [bokeh/datashader#10]

**Comment by jbednar** [comment]
I'd rather add a real request specification, not just a random id, so that browser caching is used when it really makes sense (as it will when switching between widget values, e.g. different transfer functions).  But that requires constructing some string that encapsulates everything about the request that could change.

**Comment by brendancol** [comment]
So in the PR above I DID go the UUID route.  This is a temporary fix, and http will be removed once bokeh plot frame height/width are exposed to the server side.  The other params (transfer func, agg, field...) are not actually consumed from the url, so thought that might be confusing if they are included only to bust cache.
