### ISSUE TITLE
Support 3 dimensional scatter

### ISSUE THREAD

**Issue by maresk** [bokeh/datashader#153]
Is it possible to easily extend the ds.pipeline to support 3d scatter ? Holoviews has a great functionality for it but dataset size is a major limitation.

**Comment by jbednar** [comment]
HoloViews uses matplotlib's 3D scatter, which will only give you meaningful plots for very sparse data, because otherwise all the foreground data will occlude the rest of the data.  So even if the Matplotlib 3D code could handle very large datasets, the resulting visualization is not likely to be very useful for large datasets except in special cases (e.g. datapoints falling on a 2D manifold in the 3D space).

Datashader could be extended to aggregate in 3D as well as 2D, but because it works in terms of pixels/voxels, the results would have to be rendered volumetrically, which would need a special 3D rendering library for you to be able to view it.  By the time you're using such a library, I'm not sure that datashader would be of much benefit; 3D libraries have their own graphics processing pipelines that are probably more suitable.  In any case all of the datashader pipeline would have to be rewritten in 3D, which isn't a lot of code, but would still be a maintenance burden that would need some good justification to do.  And of course volumetric rendering has the same problems of occlusion that a 3D scatterplot would, though these can be eased with transparency, slicing, and various other techniques.

So, the short answer, is, no, it's not something that could *easily* be added.

**Comment by philippjfr** [comment]
Providing ways for HoloViews and Datashader to interact is something we'll be investigating in the coming months. All the points @jbednar has made are good reasons why datashader isn't suited toward true 3D scattering. However using HoloViews you could easily chunk the data into multiple z-slices along the third dimension, which you could let you explore the '3D scatter' as 2D slices of a 3D volume. That's definitely something worth looking into and is probably something we'll tackle in HoloViews or a HoloViews extension in future. So just keep an eye open for HoloViews announcements in the coming months.

**Comment by jbednar** [comment]
That's an interesting idea, and not much work!  Yes, we should soon have an object in HoloViews that wraps a datashader 2D image, and once we have that, providing a slice/stack viewer for 3D wouldn't be much additional work, and would be useful!

**Comment by maresk** [comment]
That would be great, a 2D slice rendering of data is actually more preferable to a volumetric rendering for anything a little more involved than simply looking at the blob which in most cases only display data on the surface while masking the interior of the volume for a sufficiently dense area. If one needs to peruse the data in any extra detail, a 2D "flight" through the blob volume is what actually does the job.

**Comment by whyboris** [comment]
There is a successful implementation of a 3D scatter plot on [StackOverflow](https://stackoverflow.com/questions/46378367/implementing-a-full-3d-scatter-with-bokeh-in-python) that might be of value to some 👍

**Comment by jbednar** [comment]
You can also use the full datashader-like 3D heatmaps provided by the [vaex project](http://vaex.astro.rug.nl).
