### ISSUE TITLE
Make it pip instalable

### ISSUE THREAD

**Issue by fccoelho** [bokeh/datashader#164]
Can you make it pip installable?
if not, why not?

**Comment by brendancol** [comment]
@fccoelho sounds pretty doable.  We are getting ready for another release soon which sounds like a good time to get this up on pypi. @JimB any thoughts on this?

**Comment by jbednar** [comment]
We could certainly put datashader itself on pypi, which is simple since it doesn't have anything but pure Python in it.  However, datashader depends on numba, which in turn depends on some heavy-duty non-Python libraries like LLVM, and anyone who tries to get LLVM running based on a pip install is likely to have all sorts of headaches.  That makes me reluctant to put datashader on pypi, because then people would try to install it using pip, and will thus have lots of problems.  Basically, if you install datashader using conda, it will all work just fine; if you tried to do it via pip you'd have headaches that we don't have the resources to support.

**Comment by NervenCid** [comment]
Could you make a binary installer or something like this?:

http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by bryevdv** [comment]
Those are wheels. You can't make a wheel for LLVM because it is a C++ library, not a python package. Solving this problem is why conda exists.

**Comment by mjb6z9** [comment]
The pip installation would still be very useful even it also noting that the llvm libraries need to be installed at the system level. +1 for pip installer.

**Comment by bryevdv** [comment]
speaking entirely in my role maintaining another, different OSS project: that's easy to enough say if you aren't the person who will be getting the bug reports, or having to deal with the inevitable bad publicity *"XYZ doesn't work!"* (even though it **does** work just fine)

**Comment by jbednar** [comment]
Right.  All other things being equal, I'd be very happy to make datashader available on pypi -- the more users, the better!  All of my other projects are on pypi, for instance (holoviews, imagen, param, etc.).  But all other things *aren't* equal, and none of my other projects have required binary dependencies.  

We could consider making a version of datashader that doesn't depend on numba, so that it could go on pypi, but it would then be so slow that it would be unusable.  So I think that's a nonstarter.  

Meanwhile, anyone is welcome to install datashader from git, if you want to take responsibility for the dependency management yourself, and in fact you can already use pip to do so via git, with a special pip command.  But it's better if I don't post that command here, because I want people to be fully aware that if they go down that route, they are taking responsibility for everything themselves.

For everyone else, use conda! :-)

**Comment by NervenCid** [comment]
I cannot use conda without annaconda :(

**Comment by NervenCid** [comment]
how can enble conda? that change much

**Comment by fccoelho** [comment]
Many packages in the scientific python ecosystem depend on C,C++ or Fortran
code and have been distributed through pypi, for years. I am sure I don't
need to list them here.
Having a non python dependency it's not a reason for reinventing a
perfectly fine and improving package manager such as pip. I am sure conda
must have another reason for existing. I always thought it existed to make
Windows users life easier. Which is a good thing in itself.
Em 16/06/2016 17:25, "James A. Bednar" <notifications@github.com> escreveu:

**Comment by NervenCid** [comment]
conda was cool... but now it is impossible use it without anaconda and they don't have python idle... pip sucks sometimes but i blame the developers

**Comment by bryevdv** [comment]
Many packages have been distributed painfully and terribly for years. Conda exists because ~4 years ago Guido told the scientific community that if the existing packaging tools didn't fit the needs of the scientific python community, then they should be build their own solution (literally he said that, I was in the room). So, that is why conda exists. At this point, years later, it's no re-invention, it is well-established and extremely heavily used. 

@fccoelho are you offering to maintain all pip build, distribution, and user support?

@NervenCid you can use conda with "miniconda" which is a minimal install that contains on python and conda. It's also false that it does not contain IDLE, that is part of python. I just tried ` python -m idlelib.idle` and it worked perfectly well as expected.

**Comment by NervenCid** [comment]
I did'nt know that, i will try

but i hope that datashader 

I hope that datashader comes to pip,

I know that pip have been sucks for years, but (its only my opinion) continuum is very restrictive (and miniconda and conda don't work if you use python from their official website) with the idle (but i will try the miniconda)

**Comment by bryevdv** [comment]
@NervenCid There is now a completely 100% driven community effort to build and distribute conda packages, independent of Continuum: https://conda-forge.github.io

**Comment by NervenCid** [comment]
wow @bryevdv  ididn't know that too (sorry for my english)...

My situation is this:

I installed the normal Python 3.5 from official Python website
I tried to install conda via pip
conda didn't work
I tried to install each conda package independently via pip or unofficial python installers 
I didn't find your package
Many packages didn't work
With the pass of time i find more difficult to use python

How conda-forge works? Should i install miniconda from continumm? or is a separately from continuum i didn't find any download link

Thank you

**Comment by bryevdv** [comment]
@NervenCid install miniconda, then run the one `conda config` command listed here:

https://conda-forge.github.io/#about

Then you can automatically install from the community condo-forge channel

**Comment by NervenCid** [comment]
@bryevdv  thank you for your answer

I know that it is too soon

but conda is open source? i see that you have plans for fork it

this have idle too? 

Thank you and sorry for my english again

**Comment by bryevdv** [comment]
@NervenCid apologies but I think you have some confusions. Conda is open source (BSD licensed) I have no plans to for it, and I'm not aware of any one else that does either. It's easy to point conda at any location for packages like `conda-forge` does. There's no need to fork just to let conda use a new, different package repository. 

Regarding IDLE, it is built into python. It has nothing to do with conda. Any python, including those installed with conda, have IDLE included.

**Comment by NervenCid** [comment]
I though that conda was propietary because the pip version of conda did'nt work any more

If i download conda via pip and try to use it, and i was getting errors

There is some form to use pip downloaded conda? i installed miniconda

the comand python -m idlelib.idle is working as you said, but i don't find the .exe of the idle in order to make a shortcout....

Thank you

**Comment by bryevdv** [comment]
@NervenCid "pip install conda" is not really a support use of `conda`, because `conda` needs to store extra metadata to function. The recommended why to get "just conda" is to install Miniconda. The fact that Miniconda installs in a simple directory in your home directory, and does not touch the system python, is a ***hugely compelling feature*** for many people, such as myself. All of that is independent of whether `conda` is open source. It is up on GitHub, with a BSD license, and anyone can fork it or make pull requests or issues against it.

**Comment by NervenCid** [comment]
Thank you 
}I Have been proving with tkinter code but python is crashing

there are issues or restrictions in realation with User interfaces?

**Comment by NervenCid** [comment]
@bryevdv  i had tried this code and work in official python and didn't worked on miniconda python (is crashing):

#Importamos las librerias
import matplotlib
matplotlib.use('TkAgg')
from numpy import arange, sin, pi
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg,NavigationToolbar2TkAgg

#Importamos el 'Backend' por defecto de matplotlib
from matplotlib.backend_bases import key_press_handler
from matplotlib.figure import Figure
#Importamos sys VERIFICANDO la version de Python
import sys
if sys.version_info[0] < 3:
    import Tkinter as Tk
else:
    import tkinter as Tk

#Creamos un objeto 'Ventana' en donde llamaremos
#todos los controles de Tkinter
Ventana = Tk.Tk()
Ventana.wm_title("MatplotLib y Tkinter")

#Parametrizamos el 'plot'
f = Figure(figsize=(3,3), dpi=80)
a = f.add_subplot(111)

#Creamos los arreglos a graficar
t = arange(0.0, 1.0, 0.001)
a0 = 5
f0 = 3
s = a0*sin(2*pi*f0*t)

#Creamos la grafica para conectarla
l,=a.plot(t,s,lw=4, color='red')
a.axis([0, 1, -100, 100])

#Creamos un 'canvas' (o lienzo) en el cual vamos
#A embeber la grafica
canvas = FigureCanvasTkAgg(f, master=Ventana)
canvas.show()
canvas.get_tk_widget().pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)
canvas._tkcanvas.pack(side=Tk.TOP, fill=Tk.BOTH, expand=1)

#En la siguiente funcion lo que se hace es actualizar
#los valores amplitud y frequencia a medida que se modifiquen
#los valores de los 'sliders'
def update(val):
    amp = Slider1.get()
    freq = Slider2.get()
    l.set_ydata(amp*sin(2*pi*freq*t))
    #Redibujamos la grafica
    canvas.draw()
    print('Amplitud: {v}'.format(v=amp))
    print('Frecuencia: {v}'.format(v=freq))

#Creamos y desplegamos el 'Slider1'
Slider1 = Tk.Scale(Ventana,
                   length=350,
                   orient='horizontal',
                   label='Amplitud',
                   from_=0,
                   to=100,
                   command=update)

Slider1.pack()

#Creamos y desplegamos el 'Slider2'
Slider2 = Tk.Scale(Ventana,
                   length=350,
                   orient='horizontal',
                   label='Frecuencia',
                   from_=0,
                   to=10,
                   resolution=0.01,
                   command=update)

Slider2.pack()

#Asignamos valores por defecto para 
#'Slider1'y 'Slider2'
Slider1.set(50)
Slider2.set(5)

#Reiniciamos los valores iniciales de la grafica
def reset():    
    Slider1.set(50)
    Slider2.set(5)    

#Creamos un boton que llama a la funcion 'reset'
button = Tk.Button(master=Ventana, text='Reiniciar Grafica', command=reset)
button.pack(side=Tk.RIGHT)

#Creamos una funcion para cambiar los colores de la grafica
def colorfunc():
    selection = "Usted selecciono el color " + str(var.get())    
    if str(var.get())=='1':
        l.set_color('blue')
        print(selection)
    elif str(var.get())=='2':
        l.set_color('red')
        print(selection)
    else:
        l.set_color('green')
        print(selection)
    #Redibujamos la grafica
    canvas.draw()

#Creamos un 'Radiobutton' que llamara a la funcion 'colorfunc'
#y cambiar el color de la grafica a Azul
#Var es un valor que ira cambiando a medida que se activen
#Los diferentes 'Radiobuttons'
var = Tk.IntVar()
R1 = Tk.Radiobutton(Ventana,
                    text="Azul",
                    variable=var,
                    value=1,
                    command=colorfunc)
R1.pack()

#Creamos un 'Radiobutton' que llamara a la funcion 'colorfunc'
#y cambiar el color de la grafica a Rojo
R2 = Tk.Radiobutton(Ventana,
                    text="Rojo",
                    variable=var,
                    value=2,
                    command=colorfunc)
R2.pack()

#Creamos un 'Radiobutton' que llamara a la funcion 'colorfunc'
#y cambiar el color de la grafica a Verde
R3 = Tk.Radiobutton(Ventana,
                    text="Verde",
                    variable=var,
                    value=3,
                    command=colorfunc)
R3.pack()

#Descomentamos estas dos lineas si deseamos mostrar
#La barra de herramientas de Matplotlib:
#toolbar = NavigationToolbar2TkAgg( canvas, Ventana )
#toolbar.update()

#Mostramos en pantalla
Tk.mainloop()

**Comment by NervenCid** [comment]
@bryevdv  sorry i am new on github... but the point is that the code works fine in normal python and python crashes with the python of miniconda

**Comment by jbednar** [comment]
Just to clarify, this is the github site for datashader, not for tech support for Python in general.  I'll go ahead and close this issue now, since I think it has resolved its original purpose.  For general support of Python tools, you could try StackOverflow, or perhaps pay for support from an experienced developer.  If you want to use pip for installing packages with C/C++-library dependencies, go for it, but as a pip user for more than a decade I can guarantee you will be making your life vastly more difficult than it needs to be, and you will also be missing out on major performance gains that you could have had if you let conda pick the correct optimized binaries for each platform.  In any case, good luck!

**Comment by bryevdv** [comment]
@NervenCid this issue is not really the place to continue this discussion as @jbednar but I wanted to make two quick last comments:

* when posting code to GH issues, please use "code" markup, otherwise, all formatting and indentation is last (as it was in your post above)

* also, after fixing the indentation, etc, your code works perfectly well with  anaconda for me:
<img width="301" alt="screen shot 2016-06-16 at 11 26 26 pm" src="https://cloud.githubusercontent.com/assets/1078448/16140785/f5c7d15e-3419-11e6-8da5-ff36232eb239.png">

**Comment by cdeil** [comment]
I have Numba from Macports and tried `pip install datashader` and was surprised that it didn't work. Add a sentence to the README and docs that explicitly say `pip install datashader` doesn't work because it's not on PyPI?

**Comment by jbednar** [comment]
Good idea; I've added a note to the readme: https://github.com/bokeh/datashader/commit/77147d4d52e87f0170d85542f8edab85dc40faee

**Comment by cdeil** [comment]
@jbednar - Thanks!
