### ISSUE TITLE
How to save InteractiveImage in a html file

### ISSUE THREAD

**Issue by ngoix** [bokeh/datashader#193]
Thank you for this very useful library.
Naive question but I couldn't find the answer, how can I save an InteractiveImage ? (I'm not using a notebook)

**Comment by jbednar** [comment]
Glad you find it useful!  I'm not sure what you mean, though.  InteractiveImage only works in a notebook, and would only be useful in a notebook.  E.g. if you have a call `InteractiveImage(p, create_image)`, if what you want is to save an image directly, just call `create_image()` to get the image as a Python object, or `from datashader.utils import export_image ; export_image(create_image(),"filename")` to save it to a file.

**Comment by ngoix** [comment]
Thanks for your answer @jbednar . To be more precise, I'd like an interactive image (with a callback for zooming etc), saved in a html file. Pretty the same as does `InteractiveImage`, but not in a notebook.
Does `export_image` allow to do that?

**Comment by jbednar** [comment]
If you are hoping to save the full, zoomable plot into a standalone HTML file, you should just use Bokeh directly, not datashader, because that's how Bokeh works: it encodes the full set of data as JSON and exports an HTML file that includes the JavaScript necessary for interacting with the plot, along with the JSON-format data used in the plot. Doing so lets you have a standalone HTML file, but a standalone HTML file will never work for larger datasets that would crash your browser because of the enormous files required.

Datashader is expressly designed *not* to put the full set of data into an HTML file; it's for use when doing so would not be feasible.  Datashader *requires* that the data be kept out of the browser, managed by an external Python process, because it is designed for cases when the browser cannot handle the full set of data.  E.g. if your dataset has 1 million points, encoding that as JSON would result in an HTML file that would be unreadable with today's browsers, so datashader keeps that data stored efficiently in a Python process, ready for delivery as an image into the browser so that the browser only ever sees a fixed-size data structure.  So you can either have standalone HTML files, or the ability to handle large datasets; you cannot have both (with today's browser technologies).

**Comment by poliu2s** [comment]
Hi @jbednar, I have been using datashader with bokeh and its been amazing to visualise my large dataset. I have plugged it into my pipeline and now I want to take 'snapshots' of the interactive image. 

As an example this is the plot I have created with InteractiveImage:
![image](https://cloud.githubusercontent.com/assets/1176661/21282179/b3f56026-c446-11e6-851d-c39c150110ba.png)

But when I save the tf.shade, the image save doesn't have the bokeh plot params:
![image](https://cloud.githubusercontent.com/assets/1176661/21282195/d6b7d594-c446-11e6-8eb5-758aefea8141.png)

Is there a way to save an non-interactive 'snapshot' image of the bokeh plot?

**Comment by jbednar** [comment]
The output of tf.shade is just a bare image, with no axes or labels, and it sounds like you are asking about exporting the entire Bokeh plot, with all its axes and labels? That's an issue for Bokeh rather than datashader, as datashader should work fine with any options for export supported by Bokeh.  Search for "Bokeh export" to see what those options are, but none are very satisfying at present.  

InteractiveImage is actually a tiny bit of code borrowed from HoloViews, and we've now added datashader support to the current Github master of holoviews (to be released as version 1.7). With holoviews you can easily choose between using matplotlib and using bokeh to view your plots, and the advantage of the matplotlib backend is that matplotlib figures can be export to svg or png easily.  See an example of using holoviews with datashader [here](https://anaconda.org/jbednar/census-hv-dask/notebook), where you can change 'bokeh' to 'matplotlib' to use matplotlib instead (and remove some of the axis=None lines to show the axes).  See the Exporting tutorial at holoviews.org for options for exporting plots.
