### ISSUE TITLE
linked brushing?

### ISSUE THREAD

**Issue by amueller** [bokeh/datashader#204]
Is linked brushing planned or already there?

**Comment by jbednar** [comment]
Linked brushing could easily be implemented as for hover(), i.e. selecting a subset of the aggregate cells, but it's not well defined what to do after that.  You should already be able to implement whatever you like, as long as you are clear what you want.  

E.g. if you have two different datashader plots in the same app that are showing different data plotted on the same axes and with the same binning, you could make linked brushing select the corresponding aggregate bins in each one.  Or if you had a non-datashader Bokeh plot alongside a datashader plot with the same axes, then you could select a set of aggregate bins in the datashader plot, then find all the matching datapoints in the Bokeh plot. 

Going the other way is *very* undefined -- if you select a set of specific Bokeh plot points, it's unclear how that should be reflected in the bin-based datashader plot; perhaps it would then select all the aggregate bins that the selected points would fall into were they to be put into the aggregation?  That could be computed, but would be very tricky to do.

Other cases are also problematic; e.g. it's not clear what a selection of a certain set of aggregate bins on one datashader plot would mean for a different gridding in another datashader plot, and in general there is nothing to make different datashader plots have the same gridding at present.

Given all these complications, it's unlikely that we will support linked brushing for datashader plots any time soon, but it's definitely possible in principle, and wouldn't be that hard to do for any one particular case that applied to your application.

**Comment by knutago** [comment]
Discovered this closed issue through a Google search, and wanted to make a comment.  I think a way in which linked brushing could be well defined is if the brushing were used to update the category of individual data points within a plot, so that subsequent datashader plots could reflect the update.  For example, brushing an x vs. y datashader plot would assign a category 'selected' to the individual points in the dataset bounded by the brushing.  The selection could trigger recomputation though the datashader pipeline of the x vs. y plot as well as other plots, e.g. w vs z, with updates to reflect the new categories.

**Comment by jbednar** [comment]
That's an interesting suggestion.  Just to be clear, there are no individual data points within a datashader plot. Datashader aggregates the data incrementally, adding each new batch of data points to the existing incremental aggregates in a way that never involves storing all the individual points.  But assuming you mean changing the data points in the original source by doing a query based on the brushed shape of the aggregate, yes, backwards tagging them in some way would be a way to keep track of linked brushing.  We don't currently modify the original data sources, which lets us use a wide variety of data formats easily, so it could get tricky to implement...

**Comment by knutago** [comment]
Thanks for the response.  I'm sure it's not trivial, and understand that datashader doesn't store individual points.  But as I understand it in this code from the datashader pipeline notebook, doesn't the aggregate get recomputed from the dataframe when an interaction happens? i.e. in the line     

agg = cvs.points(df, 'x', 'y', ds.count_cat('cat'))

inside the callback function.  Is it not possible to modify the values of a category in the dataframe based on interactive input?

**Comment by jbednar** [comment]
Sure, that's possible, and this approach comes under the response to the original post -- you as a user can already implement this for any particular plot.  I.e. you can register a callback with bokeh that grabs the shape of the brushed area in a datashader plot, does a query on the original points, marks the category on the original data source, and then tells another plot that's using that category information to update.  At least for a box select, doing this wouldn't need any features of datashader at all -- the box select will choose an area of the axes, and you can do a query on the dataset based on this area regardless of how datashader has aggregated it.  So you can do this with Bokeh and pandas now, already, though it would be useful if we provided a good example to follow. :-) 

A lasso select is more complicated, and does depend on datashader, because arguably it should draw out a fixed set of aggregate bins, aligned to bin boundaries.  Still, something approximately correct, at least for small bin sizes, can be done independently of datashader -- the user can select a region in the real plane, which user-level code can use as a query both for the datashader plot and for any other linked plot.  So you can already do all of this yourself, it's just that I would not expect datashader to offer functionality to make it easier to do so if it needs to modify the original data source from within code in datashader/.

**Comment by knutago** [comment]
Thanks again for the response.  I will give it a go.  A good example would make it easier! :)
