### ISSUE TITLE
Dataset opensky.h5 not available?

### ISSUE THREAD

**Issue by ThomasG77** [bokeh/datashader#256]
I've seen a reference to `data/opensky.h5` in https://github.com/bokeh/datashader/blob/master/examples/opensky.ipynb but it seems there is no URL to get the data anywhere. I would have expected it in https://github.com/bokeh/datashader/blob/master/examples/datasets.yml

A mistake on my side?

Thanks

**Comment by miguelgfierro** [comment]
Same thing here

**Comment by jbednar** [comment]
Unfortunately, no, opensky.h5 is not available for download. As it says at the top of opensky.ipynb:

> The original database was 1.1GB, leading to an HDF5 subset that is 600MB. Both those files are  too large to distribute with datashader, but you can collect your own data since it's a public site.
Once you have the data, ...

More importantly, the [terms of use for the Open Sky Network](https://opensky-network.org/about/terms-of-use) forbid redistribution of datasets that they provide, although it is not clear to me whether and how those terms apply to data obtained via the public API rather than as a complete dataset.  But you can certainly ask Open Sky Network for the data, and if you can get them to agree to make a subset of it available for download, we would be happy to modify this notebook to fetch it from there instead so that it will work for everyone.

**Comment by ThomasG77** [comment]
Thanks for the follow up.
I didn't understand well and now it's clear.
