### ISSUE TITLE
How to visualize an interactive image in a saved jupyter notebook

### ISSUE THREAD

**Issue by miguelgfierro** [bokeh/datashader#264]
Hi, I'm doing the project described in #263 and I just realized that I can not show the interactive image in a the notebook that is saved in github. I can see the image correctly when I run the system in my server, however I would like to show the image also when I upload the code to github. 

This is the code:

```python
plot_width  = 850
plot_height = 600
x_range = (-2.0e6, 2.5e6)
y_range = (4.1e6, 7.8e6)
def create_image(x_range=x_range, y_range=y_range, w=plot_width, h=plot_height):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.line(df_agg_mercator, 'Latitude', 'Longitude',  ds.count())
    img = tf.shade(agg, cmap=Blues9, how='eq_hist')
        
    return img

def base_plot(tools='pan,wheel_zoom,reset',plot_width=plot_width, plot_height=plot_height,**plot_args):
    p = figure(tools=tools, plot_width=plot_width, plot_height=plot_height,
        x_range=x_range, y_range=y_range, outline_line_color=None,
        min_border=0, min_border_left=0, min_border_right=0,
        min_border_top=0, min_border_bottom=0, **plot_args)
    
    p.axis.visible = False
    p.xgrid.grid_line_color = None
    p.ygrid.grid_line_color = None
    
    return p

ArcGIS=WMTSTileSource(url='http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{Z}/{Y}/{X}.png')
p = base_plot()
p.add_tile(ArcGIS)
InteractiveImage(p, create_image)
```
Is there a way to do this? I would be happy to have a screenshot of the image (whitout being interactive)

**Comment by philippjfr** [comment]
It's not quite clear to me why this isn't working because ``InteractiveImage`` just uses ``_repr_html`` to publish the ``notebook_div``. I'll have a look at it though.

**Comment by miguelgfierro** [comment]
It can't be done because bokeh uses a python kernel to load the dynamic image and github doesn't have one: http://stackoverflow.com/questions/32518342/why-my-bokeh-plots-doesnt-work-on-github

**Comment by jbednar** [comment]
I don't think it's because of github not having a Python kernel.  For instance, neither do nbviewer or anaconda.org, but both of those display the plots just fine (without interactive regeneration of the aggregate array), e.g.: https://anaconda.org/jbednar/nyc_taxi/notebook

I think it's just the first of the issues at that stackoverflow link, i.e., that Github doesn't process the javascript.  Perhaps someday we can convince github to make an exception for saved Jupyter notebooks, as nbviewer and anaconda.org manage to do it.  But at least github partially renders notebooks nowadays, which is an improvement!

**Comment by philippjfr** [comment]
>I think it's just the first of the issues at that stackoverflow link, i.e., that Github doesn't process the javascript. 

The thing is there is nothing different about the initial ``InteractiveImage`` plot when compared to regular bokeh plots except the mechanism by which the plot is embedded, i.e. using ``_repr_html`` instead of ``IPython.core.displaypub.publish_display_data``. So in theory I see no reason why this shouldn't just work.

**Comment by jbednar** [comment]
But regular Bokeh plots don't work on github either.

**Comment by philippjfr** [comment]
Ah, of course, that's a good point, I never use GitHub rendering. So yes, nothing we can do here, and not specific to ``InteractiveImage``.

**Comment by jbednar** [comment]
Right; it's not specific to datashader; any notebook cells that depend on embedded javascript won't display at all.  I'm not sure if Bokeh could somehow substitute a static HTML copy of the plot for use in such cases, but if so that would be handled as part of Bokeh rather than datashader.
