### ISSUE TITLE
Question: Is it possible to make rasters that can be mapped with tools like leaflet?

### ISSUE THREAD

**Issue by ranranking** [bokeh/datashader#267]
Hello, I am new to this project. I am wondering whether it is possible to create rasters that can be mapped? For example, how the make the output from the Census example to be mapped in tools like leaflet?

**Comment by jbednar** [comment]
It sounds like you're asking whether it is possible to render a set of rasterized tiles so that you can set up a tileserver, e.g. for use with leaflet.  Yes, you can definitely do that.  Here's an example of someone who rendered an 8K by 8K image then chopped it up into tiles for such a server:
https://proseandcode.co.uk/beta_gtr_viz

Once he had the image, he didn't need to use anything from datashader to create his site, and I'm not sure what tools he used.  It should be pretty straightforward to write some scripts to do this, and it would be great to provide a simple example so that datashader users could follow a recipe, but we have not yet done that.

**Comment by ranranking** [comment]
Yes, I think that is not a problem with datashader. I need to give the output image some geoinformations, and then tile them. I know how to tile a raster, but I haven't tried it with datashader image. But thank you very much for the help!
