### ISSUE TITLE
Create a grid of linked interactive bokeh-datashader plots

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/datashader#290]
I would like to create a grid of bokeh-datashader plots using something like:
```
plots = []
plots.append(InteractiveImage(p1, image_callback1))
plots.append(InteractiveImage(p2, image_callback2))
plots.append(InteractiveImage(p2, image_callback3))
bokeh.layouts.gridplot([[plots[0], plots[1], plots[2]]])
```
while also linking the plot ranges using something like this
```
for p in plots:
    p.x_range = plots[0].x_range
    p.y_range = plots[0].y_range
```
so that adjusting the range of one of the plots also adjusts the range of all the plots, while updating the datashader displays.  I realize what I have does not work, because `InteractiveImage` does not return a bokeh plot object.  Is there currently a way to do this?

**Comment by StevenCHowell** [comment]
The following accomplishes what I am trying to do, without the interactivity.
```
plots = []

for i in range(1, 7):
    x2_range = x2_df['q{}'.format(i)].min(), x2_df['q{}'.format(i)].max()
    
    p = bokeh.plotting.figure(width=300, height=300, title='chi-square matching Q{}'.format(i), 
                              x_axis_label='Rg', y_axis_label='chi-square', 
                              x_range=rg_range, y_range=x2_range)
    
    canvas = datashader.Canvas(plot_width=width, plot_height=height, x_range=rg_range, y_range=x2_range)
    agg = canvas.points(x2_df, 'rg', 'q{}'.format(i), agg=datashader.count())
    img = datashader.transfer_functions.shade(agg, cmap=Viridis256, how='eq_hist')
    
    p.image_rgba(image=[img.data], x=rg_range[0], y=x2_range[0],
                 dw=[rg_range[1]-rg_range[0]], dh=[x2_range[1]-x2_range[0]])
    
    plots.append(p)
    
    p.x_range = plots[0].x_range
    p.y_range = plots[0].y_range
    
    
plot_grid = bokeh.layouts.gridplot([[plots[0], plots[1], plots[2]], [plots[3], plots[4], plots[5]]])
bokeh.io.show(plot_grid)
```

**Comment by jbednar** [comment]
It might be possible to modify InteractiveImage to do this, but instead I think you ought to be using [HoloViews](http://holoviews.org) for anything but a single, isolated datashader plot.  InteractiveImage is a tiny piece that we originally took out of HoloViews to show off how datashader works, but for anything ambitious, I'd recommend just using HoloViews itself.  

HoloViews is formulated at a level one step higher than Bokeh, which makes it vastly simpler to do things like dynamically updating an underlying plot, as InteractiveImage needs to do, while also embedding the plot into a larger layout.  E.g. combining two Bokeh plots X and Y with linked axes in HoloViews is normally just "X+Y".

We are gearing up for a release of HoloViews that has documentation for how to use it with datashader, but meanwhile there are examples on this [HoloViews Datashader notebook](https://anaconda.org/philippjfr/holoviews_datashader).  Code for doing what you outline above should be one or two lines, in HoloViews.  Basically, use NdLayout if your "Q" values can be interpreted as a dimension (values along some zxis), and otherwise use Layout (which is what the "+" operator constructs).

**Comment by jbednar** [comment]
HoloVIews 1.7 has been released, and can be installed using `conda install -c ioam holoviews`.  This version includes full support for datashader, as outlined in the greatly expanded [HoloViews Datashader notebook](https://anaconda.org/jbednar/holoviews_datashader).  You should be able to run that notebook and see how to combine multiple Datashader plots into any arrangement, e.g. `(q1+q2+q3+q4+q5+q6).cols(3)`.  Note that datashader itself has not yet been released, so until it is you'll need the git master version.

**Comment by alexey-petrenko** [comment]
I was wondering if it's possible to dynamically filter the data in the linked HoloViews Datashader plots based on the Zoom? For example if I have a large number of particles each with coordinates and velocities x,y,vx,vy shown as two linked plots: (x,y) and (vx,vy). I want to show (vx,vy) only for the particles which are currently visible in the x-y plot.

This is very similar to the Bokeh's CustomJS for selection or Zoom:
http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-selections

Thanks!

**Comment by jbednar** [comment]
I think that's a HoloViews question, because the zoomed region is available from Bokeh whether or not the plot includes any Datashader images.  I'd guess it would be fairly simple to do that using HoloViews Streams, but if you go through the [Streams Tutorial](http://holoviews.org/Tutorials/Streams.html) and don't see how to do it, please open an issue there explaining what you tried and what you were hoping it would do.

**Comment by alexey-petrenko** [comment]
Many thanks! Using Streams it is easy to [link the datashader plots](https://anaconda.org/petrenko/linking_datashaders/notebook) dynamically indeed.

**Comment by jbednar** [comment]
Great!  Thanks for the notebook link!
