### ISSUE TITLE
downloading examples

### ISSUE THREAD

**Issue by lukereding** [bokeh/datashader#322]
I'm having some trouble downloading the examples. I've followed the instructions [here](https://github.com/bokeh/datashader/tree/master/examples#datashader-examples) and [installed a conda environment with all the required packages](https://github.com/bokeh/datashader/blob/627c9b70a56c5a0f58dabf9f1da4f4836786b727/README.md#installation).

```
(ds) 0214-user:Desktop $ cd ~
(ds) 0214-user:~ $ python -c "from datashader import examples ; examples('datashader-examples')"
(ds) 0214-user:~ $ echo $?
0
(ds) 0214-user:~ $ find . -type d -name "datashader-examples"
(ds) 0214-user:~ $ cd datashader-examples
-bash: cd: datashader-examples: No such file or directory
(ds) 0214-user:~ $ find . -mmin -1 -type d | grep data

```

Is there something I'm missing?

**Comment by jbednar** [comment]
Looks like there must be some silent error preventing execution of that function, which shouldn't happen!  I'll have to investigate.

**Comment by lukereding** [comment]
I should mention that I'm running the latest OSX; running the same commands using [this](https://hub.docker.com/r/continuumio/anaconda/) docker image results in the `datashader-examples`folder with all the notebooks as expected.

**Comment by jbcrail** [comment]
@lukereding, thanks for the additional information. This helped me confirm the behavior on macOS.

It turned out that the non-conda Python package did not install the examples. The conda build had an extra step that installed the examples.

Thus, since datashader was pre-installed in the Anaconda distribution on docker, the instructions worked. If you uninstalled datashader from docker, then the examples would fail to be copied.

I created PR #339 to fix this.

**Comment by jbednar** [comment]
@lukereding, can you clarify how you installed datashader?  Was it from conda or via some other source?
