### ISSUE TITLE
Got the demos going but the census data seems truncated?

### ISSUE THREAD

**Issue by dartdog** [bokeh/datashader#397]
using the census ipynb..
The census snappy Parquet file seems to only have 
76668751 records from using the census notebook I did also dl and extract the file from census as suggested in the notebook but it seems that is not used and the parquet file is..
%%time
df = dd.io.parquet.read_parquet('data/census.snappy.parq')
df = df.persist()
df.index.nunique().compute()
76668751
All works great but don't know what data I'm missing or how to fix it? 

FWIW I have 64gb real memory available..

**Comment by jbednar** [comment]
Lucky you, with 64GB! :-)

Dask dataframes can be confusing, because of operations that report values for a single partition rather than the total array.  If you do ``len(df)`` you should see the actual total number of rows across all partitions, which is 306675004.  The dask documentation should have explanations, and if it's not clear, please file an issue on the dask site.

**Comment by dartdog** [comment]
Super helpful might consider putting that in the demo for following dummies! since the tail shows the truncated tail as well which is what started me trying to figure it out! Sorry!

**Comment by jbednar** [comment]
Right; the notebook should definitely mention this issue (as the behavior changed since the existing text was written).

**Comment by jbednar** [comment]
Plus the additional complication that simply printing "len(df)" on a dask dataframe can be expensive, because it forces the entire array to be read in even if you are only using one part of it!

**Comment by jbednar** [comment]
Ok, I've updated the tutorial to explain this a bit better: https://anaconda.org/jbednar/census/notebook
