### ISSUE TITLE
nyc_taxi data question for demo nyc_taxi notebook

### ISSUE THREAD

**Issue by dwervin** [bokeh/datashader#413]
I have tried to run your Jupyter notebook for nyc_taxi data with datashader.  On the video from SciPy 2016, your data shows x,y data but the nyc_taxi data I downloaded uses latitude and longitude.  I think that's why I can't see anything plotted.  

Where did you get the X,Y data in your demo?  Is this calculated from a transformation and then loaded?

Also, it's a little unclear to me from the code in the notebook how it plots geo data.  Where does it get the map that is displayed?  I don't see that called in the code.

I appreciate your help.

Thanks

**Comment by jbednar** [comment]
The example data files that we ship contain x,y data in Web Mercator coordinates, originally calculated using datashader.utils.lnglat_to_meters and then saved to a new dataframe.  The docstring in that file shows how to use that function.

If you have a dataset in lng,lat, you don't need to convert it if all you want to show is the data itself, but the coordinates do need to be converted to Web Mercator if you want to overlay points with a map in Bokeh, because Bokeh only supports Web Mercator map projections.

I'm not sure which notebook you mean, but if it's nyc_taxi.ipynb, the map is added by the line ``p.add_tile(STAMEN_TERRAIN)``.  The map comes from external server, in the form of image tiles covering whatever space is shown.

**Comment by apiszcz** [comment]
FYI, to go from lat,lon in degrees decimal to WEBMERCATOR.


```
inProj = Proj(init='epsg:4326')
outProj = Proj(init='epsg:3857')
def wgs84_2_webmercator2(row):
    xwm,ywm = transform(inProj,outProj,row['lon'],row['lat'])
    return pd.Series([xwm,ywm])

```

**Comment by dwervin** [comment]
Thanks guys.  That got me on track.  I was able to convert within the same dataframe and the points plotted on the map.

I'm a little new to Python, Anaconda, and Jupyter notebooks, but so far I think whole platform and community of users and developers is fantastic.

I appreciate you taking the time to respond.
