### ISSUE TITLE
datashader on pypi

### ISSUE THREAD

**Issue by stonebig** [bokeh/datashader#421]
Why is Datashader still not on PyPi ? via a wheel, you can specify the dependancy on numba, then on llvmlite, ... etc ... etc... so the sentence `Datashader is not currently available on PyPI, to avoid broken or low-performance installations that come from not keeping track of C/C++ binary dependencies such as LLVM (required by Numba).` doesn't seem to make sense, and low performance is not an issue in worst case.

**Comment by jbednar** [comment]
As far as I know all the issues mentioned there still apply:

 - The datashader team could make a wheel, but datashader doesn't include any binary components, so that wouldn't help anything
 - The numba team has not to my knowledge made a numba wheel; last I heard there were some technical issues that were preventing that, but I don't know the current status.
 - Once there is a numba wheel, we can very easily make a pip release of datashader, but until then there's no point
 - We could fairly easily make a low-performance version of datashader that does not depend on numba, but we don't have any interest in doing so -- we ourselves only use datashader for large datasets, so would never use some hobbled version of it anyway.  

If you're interested in supporting low-performance datashader by making numba optional, I'd be happy to consider a PR, but otherwise I don't think there's anything that datashader can do about this...
