### ISSUE TITLE
Doesn't work with Spark DataFrame

### ISSUE THREAD

**Issue by filipyoo** [bokeh/datashader#451]
I've tried to run a visualization plot using the `points()` method like : 
`cvs = ds.Canvas(plot_width=plot_width, plot_height=plot_height, x_range=x_range, y_range=y_range)
agg = cvs.points(pandas_df, 'pickup_longitude', 'pickup_latitude') 
img = tf.shade(agg, cmap=["white", 'darkblue'], how='eq_hist')`
This works perfectly, since `pandas_df` is a Pandas DataFrame. But when it is a PySpark DataFrame, errors occur:

`AttributeError                            Traceback (most recent call last)
<ipython-input-17-187dd2d2128e> in <module>()
      1 cvs = ds.Canvas(plot_width=plot_width, plot_height=plot_height, x_range=x_range, y_range=y_range)
----> 2 agg = cvs.points(spark_df, 'pickup_longitude', 'pickup_latitude') 
      3 img = tf.shade(agg, cmap=["white", 'darkblue'], how='eq_hist')
      4 img

/home/ubuntu/anaconda3/lib/python3.5/site-packages/datashader/core.py in points(self, source, x, y, agg)
    174         if agg is None:
    175             agg = count()
--> 176         return bypixel(source, self, Point(x, y), agg)
    177 
    178     def line(self, source, x, y, agg=None):

/home/ubuntu/anaconda3/lib/python3.5/site-packages/datashader/core.py in bypixel(source, canvas, glyph, agg)
    388     # by only retaining the necessary columns:
    389     # https://github.com/bokeh/datashader/issues/396
--> 390     if categorical_in_dtypes(source.dtypes.values):
    391         # Preserve column ordering without duplicates
    392         cols_to_keep = OrderedDict({col: False for col in source.columns})

AttributeError: 'list' object has no attribute 'values'`

Does that mean that `spark_df` is considered as a list ??

Thanks for your help !

**Comment by jbednar** [comment]
Datashader is designed using a technique called multi-dispatch that allows the same high-level code to work properly for any supported dataframe.  That said, the only dataframes currently supported are Pandas and Dask dataframes; if you want to use some other kind of dataframe like the one from PySpark you would need to look at the implementations we provided for Pandas and dask implementations (in dask.py and pandas.py) and write something similar to support PySpark.  It shouldn't be particularly painful to write, since those files are only 103 and 32 lines long, respectively. And If it's done well, I'd be happy to include that with datashader. I don't have any experience with PySpark myself, so I'd also need some test cases and examples to show that it works.

**Comment by jbednar** [comment]
Or you could just use a Dask dataframe, which should allow you to build even the largest data structure you could need, if you have a large cluster with enough memory.  You can also use Dask to work (more slowly) out of core on a single machine.

**Comment by jbednar** [comment]
Glad to hear it.  You know that you don't have to just hope, right?  If you have the time to look into how to do it, you can actually add PySpark support yourself, and we're happy to take code contributions... :-)
