### ISSUE TITLE
How do you track changes in bokeh plot ranges?

### ISSUE THREAD

**Issue by nleclercq** [bokeh/datashader#455]
Hi,

Sorry for contacting you using your GH issue tracker but I don't see any other way to do so. 

Bryan Van de Ven told me that you implemented 'something' to track changes of the 'x' and/or 'y' range of a bokeh plot. I trying  to do the same (1) but I really don't see how to obtain something working in ALL cases using the `on_change` event of both `range.start` and `range.end` attributes - which are the only thing available so far. Could you, please, tell me a word about your solution? Thanks for your help. 

(1)  I'm trying to implement a very simple downsampling mechanism for 2D images.

**Comment by nleclercq** [comment]
Ok. I have my answer. Everything is in datashader/bokeh_ext.py.

**Comment by jbednar** [comment]
Glad you found that!  If you have any other questions about how it's done, you can ask Philipp on https://gitter.im/ioam/holoviews; he wrote bokeh_ext.py based on his work on HoloViews.

**Comment by nleclercq** [comment]
I'm going to contact Philipp. Thanks!

**Comment by nleclercq** [comment]
BTW, unless I am mistaken, there's no gitter room for datashader. What's the best way to get support? I have a couple of questions and I don't know where I should ask them? Thanks.

**Comment by jbednar** [comment]
Issues are the best way.  HoloViews has developers hanging around working on HoloViews-related work most of the day, so it's easy to catch them in the gitter room.  Datashader is a more bursty project, with some intense periods of development interspersed with long quiescent periods.  But luckily the HoloViews developers work on Datashader some of the time, so that room is a reasonable place to ask questions.  That said, *I* am never there, so github issues are the way to go to reach me (or my email @anaconda.com).
