### ISSUE TITLE
Answer Question: Why are notebook calls slower than static image calls? 

### ISSUE THREAD

**Issue by brendancol** [bokeh/datashader#49]
Is throttling messed up?

**Comment by philippjfr** [comment]
The throttling uses ``_.debounce`` which waits until you've stopped interacting with the plot for x milliseconds to send an event. I set the default to 100 ms so it really shouldn't be noticeably slower but I have noticed that sometimes the callback does slow down considerably, so I think it's probably unrelated.

**Comment by brendancol** [comment]
@philippjfr ah good to know.  Had a quick meeting this morning and it came up.  Any ideas what might be causing the callback to slow down?

**Comment by philippjfr** [comment]
I don't really know to be honest. Could do some profiling inside the callback to see if it's slowing down on any step. Also let's be clear what we're talking about, when I mean it can slow down I mean that I've noticed that sometimes it's just inexplicably slow (by a factor of 2-3x) until you restart the kernel. Do you mean that or do you mean why is the callback consistently slower than a normal image display in which case the answer is probably JSON serialization in bokeh. Bokeh is very slow for large(ish) images, so much so that I rarely push images much larger than 500x500 pixels into the notebook.

**Comment by philippjfr** [comment]
Just did some profiling, the slowdown is actually not in the serialization, it's in recreating the image. Here's the timings for replotting vs. updating an existing image:

![image](https://cloud.githubusercontent.com/assets/1550771/12898966/264a3ad4-cea7-11e5-946f-1fd44d9f2c90.png)

**Comment by philippjfr** [comment]
So I did some actual profiling of InteractiveImage and came up with these numbers for the various steps in updating an image:

Regenerating the image (datashader): 415 ms
JSON serialization (bokeh): 587 ms
Computing a patch (bokeh): 369 ms
json.dumps: 39 ms

It seems JSON serialization eats up a lot of the time afterall. I don't know how bokeh server gets around this problem since even if it gets around updating the extraneous bits by generating only datasource change events it also at the very least has to serialize the image.

**Comment by jbednar** [comment]
Bryan has been discussing using a binary communication protocol, which I agree would be great.  But it's worth looking at what Jupyter is using, as generating a PNG works very quickly, even though it too has to be transferred from the Python process to the browser.

**Comment by philippjfr** [comment]
Agreed binary communication would definitely much better for large images. I was just playing with streaming a small png 400x400 to the browser in HoloViews, was getting roughly 30 fps including the plotting, if that's what you want to do I'd suggest just pushing to an IPython image widget.

**Comment by datnamer** [comment]
What about Dom diffing? Ala http://escher-jl.org/

**Comment by philippjfr** [comment]
To answer your question Jupyter just sends a base64 encoded png.

**Comment by jbednar** [comment]
@datnamer, thanks for the suggestion!

**Comment by jbednar** [comment]
Addressed in #80.
