### ISSUE TITLE
Requirements.txt should specify optional dask extras

### ISSUE THREAD

**Issue by dibidave** [bokeh/datashader#549]
In https://github.com/bokeh/datashader/blob/master/requirements.txt#L1

Instead of 
`dask >= 0.15.4`

I think it should be
`dask[bag] >= 0.15.4`

Otherwise it will not fulfill certain requirements such as cloudpickle when doing
`pip install -r requirements.txt`

**Comment by ceball** [comment]
I think this is fixed now.

However, there have been some changes - mainly that the dependencies are now specified only in setup.py. So, running `pip install -e .` should do a develop/editable install of datashader and its required dependencies into your current environment. If you also want to be able to run the tests, it would be `pip install -e .[tests]`. Or you can omit `-e` if you don't want an editable install.

We'll also soon be uploading datashader to pypi, so that `pip install datashader` will also work.

I'm going to close this issue, but please don't hesitate to re-open it if the above doesn't work for you or doesn't cover what you want.
