### ISSUE TITLE
pixel value when I click on an image

### ISSUE THREAD

**Issue by orkun** [bokeh/datashader#557]
Is it possible to get pixel value when I click on an image?
Is there any example? or how is it done?
regards

**Comment by jbednar** [comment]
Yes and no.  No, in that Bokeh [does not yet support hover for 2D objects](https://github.com/bokeh/bokeh/issues/3886). We keep meaning to address that, but it keeps getting shunted aside for higher-priority work, because it's trickily bound up into other work that's already underway.  Once it's done, you'll be able to hover over the image even in a pure HTML file (with no Python process running), but I can't promise when that will be ready.

Meanwhile, you can get the 2D coordinates of a mouse click as shown in the last cell of our [Landsat example](https://bokeh.github.io/datashader-docs/topics/landsat.html).  That approach requires a live Python server (and thus won't work in the actual HTML file linked there), but once you get the coordinates you should be able to look up the value from the datashaded array manually.

**Comment by jbednar** [comment]
Bokeh now supports image hover, as of bokeh 0.12.16, and it's supported by HoloViews 1.10.4 and GeoViews 1.5, so you should be able to use those libraries to show hover information for any datashaded plot.  See the "large data" sections of holoviews.org and geoviews.org.
