### ISSUE TITLE
How to shade an image with quantile color scale?

### ISSUE THREAD

**Issue by BigFatDog** [bokeh/datashader#566]
I'm trying to plot points with DataShader and want to render points with a quantile color scale. Would you please help me with it?

**Data:**
```
lon,lat,metric
30.771635, 108.353681, 34
30.765280, 108.351067, 85 
```

**Code:**
```
import datashader as ds
import datashader.transfer_functions as tf
import colormap_select from datashader.colors 

// shade image
cm = partial(colormap_select)
agg = cvs.points(df, lon, lat, ds.sum('metric'))
img = tf.shade(agg, cmap=cm(['green', 'yellow', 'red']), how='eq_hist')
```
**My Goal**
['green', 'yellow', 'red'] represent a quantile scale of aggregation:  [0, 33%, 66%, 100%] .
In other words:

- green color: min -> 33% * max
- yellow color: 33% * max ->  66% * max
- red color: 66% * max -> max

Is there a method to achieve this color scale? furthermore, is there a way to flexibly define color stops ([0, 33%, 66%, 100%]) ?

Thank you.

**Comment by jbednar** [comment]
Your code above can be simplified to:

```
import datashader as ds
import datashader.transfer_functions as tf

agg = cvs.points(df, lon, lat, ds.sum('metric'))
img = tf.shade(agg, cmap=['green', 'yellow', 'red'], how='eq_hist')
```

And presumably you are asking to get rid of the interpolation between green, yellow, and red that your code will produce?

![image](https://user-images.githubusercontent.com/1695496/36912834-a61daef0-1e0d-11e8-99f4-7db31bc80a60.png)

If so, you can do that by constructing a colormap that avoids interpolation:

![image](https://user-images.githubusercontent.com/1695496/36912851-b77cb3b2-1e0d-11e8-9b6b-a85436344c9d.png)

But personally, I like the interpolated one better. :-)

**Comment by BigFatDog** [comment]
That resolves my problem. Thank you so much for your timely and detailed response!

I admit that.. I still haven't understood how to use DataShader's color interpolation yet.

**Comment by jbednar** [comment]
We should presumably add an option to turn off the interpolation, but you can use this approach in the meantime.

**Comment by BigFatDog** [comment]
Hi, I have one more question: how can I apply color scale according to specific metric value?
Given the same example as shown above:
```
agg = cvs.points(df, lon, lat, ds.sum('metric'))
img = tf.shade(agg, cmap=['green', 'yellow', 'red'], how='eq_hist')
```
My goal:
- 'green': sum of metric < 100
- 'yellow': 100 < sum of metric < 500
- 'red': sum of metric > 500

Thanks.

**Comment by jbednar** [comment]
The 'how' argument of `tf.shade` accepts any function.  To make the mapping be whatever you like, you can start with the linear mapping function `lambda d, m: np.where(m, np.nan, d)`` that returns NaN where the mask is nonzero, and otherwise returns the metric value directly.  Just make it return 0 for m<100, 1 for 100<m<500, and 2 for m>500, for all unmasked bins.  You can then use the cmap defined above as before.

**Comment by BigFatDog** [comment]
Got it. Thank you for again for your weekend time!

**Comment by linwoodc3** [comment]
@jbednar , that is such an awesome example above.  I would have never thought to use the library that way; where would we find this type of instruction/example in the documentation?

**Comment by jbednar** [comment]
Glad you like our work!  The example above is an adaptation and extension of my "census_gray_redhot1_eq_hist" example in http://datashader.org/topics/census.html.  But that's just one example buried deep in between a bunch of others, and I think colormap manipulations like that are worth addressing explicitly in the user manual so that more people realize what can be done.

We're currently working on [re-implementing datashader's more advanced colormap features in Bokeh](https://github.com/bokeh/datashader/issues/609), and when we have that ready, we should include an overview in the manual of how to use colormapping to reveal your data flexibly and effectively, particularly in conjunction with the percentile interpretation of the results of `eq_hist`.
