### ISSUE TITLE
Introduction example needs to be updated

### ISSUE THREAD

**Issue by orodbhen** [bokeh/datashader#589]
The `getting_started/1_Introduction` notebook has several problems with it. 

- The path to the "taxi cab" data file is wrong, and should be `../data/nyc_taxi.csv`. 
- Trying to load the file with `dask`, as is currently coded, overwhelms the system and forces the OOM killer to kick in. The file takes several minutes to load, besides. 
- Removing the `.persist()` from the  `dask` loading call loads the file much more quickly and without freezing the system, but then the plots are very slow to render and refresh. Presumably, because `dask` isn't loading the whole set into memory anymore. 

This is all on a Linux Laptop with a Xeon Mobile processor, 16GB or RAM, and PCI solid state drive. 

The solution is to load the file with `pandas` instead of `dask`. It loads much faster, and the plotting interactions are as expected performance-wise.

**Comment by jbednar** [comment]
Thanks for letting me know about the path!  I have many copies of the nyc_taxi data lying around from various tests, and I didn't realize that in this notebook I was using one that's not currently downloaded when installing the datashader example data.  That definitely needs to be fixed.

That said, it sounds like there must be some other problem with datashader or dask on your system, because my own system also has 16GB of RAM, and doesn't have any problems like that.  For me, Dask+Parquet is very fast both for loading and rendering, and Dask is consistently faster than Pandas for loading in any scenario I tested with Parquet or CSV:

# dd.read_parquet

![image](https://user-images.githubusercontent.com/1695496/39258078-b23dc964-4878-11e8-9568-9197b43895c2.png)

# dd.read_csv

![image](https://user-images.githubusercontent.com/1695496/39258113-c7c8c202-4878-11e8-88ed-2e306ee5215b.png)

# pd.read_csv

![image](https://user-images.githubusercontent.com/1695496/39258188-fecd53b2-4878-11e8-9536-ec6f655127f9.png)

But note that if using CSV, it's going to load in all sorts of other data for the other columns that aren't used here, so we should specify the columns needed:

# dd.read_csv(usecols)

![image](https://user-images.githubusercontent.com/1695496/39258479-aa411490-4879-11e8-8228-d9b2cbaab1ff.png)

# pd.read_csv(usecols)

![image](https://user-images.githubusercontent.com/1695496/39258502-b9015d5a-4879-11e8-9111-85354b87d2fd.png)

Pandas with the usecols option for the CSV file might be slightly faster for rendering (have to do a lot of runs to be sure, and if so I'd wonder why that would be).  But Dask is vastly faster at reading in the CSV file initially, at least for me.  Can you do a similar test with the usecols option on your system, to see if you get similar results?

In any case, for this introductory example, it might be better to use Pandas anyway; I'm not showing timings, and more people understand Pandas than Dask.  So for your PR #591, I think I can merge it if you add the usecols option as above; it will slow down loading a lot compared to my current version (loading in 13 seconds instead of 1.7) but probably be more clear.

**Comment by orodbhen** [comment]
Hmm, I wonder what would be different about my install. I'm using an Anaconda env as per [these instructions](https://github.com/bokeh/datashader/blob/master/examples/README.md). Platform is Linux Mint. 

`dask` is 0.17.2 from `conda-forge`. I don't really have any experience with it outside this example. 

I tried using `pandas` with `usecols`, and it was about 3 times faster. I'll make the update and commit.

**Comment by jbednar** [comment]
I've merged the change in any case, thanks!
