### ISSUE TITLE
reversing axis ranges?

### ISSUE THREAD

**Issue by naheld** [bokeh/datashader#596]
First, thanks for a great package! I am plotting over 10000 lines using datashader/InteractiveImage. The code and plots are pretty standard:
<img width="834" alt="screen shot 2018-05-11 at 3 13 42 pm" src="https://user-images.githubusercontent.com/19242849/39942488-a121a79c-552d-11e8-9d28-cb7bfad5c935.png">

Currently the y axis ranges from 0 to 600. I would like to reverse the y axis range so 0 is at the top of the plot. However, doing so by adjusting the y_range parameter results in an empty image:
<img width="775" alt="screen shot 2018-05-11 at 3 14 37 pm" src="https://user-images.githubusercontent.com/19242849/39942523-ba9621f8-552d-11e8-8e52-da49744d23b4.png">

The problem isn't with Bokeh/InteractiveImage because I get an empty dataframe even when I don't call to it:
<img width="822" alt="screen shot 2018-05-11 at 3 15 10 pm" src="https://user-images.githubusercontent.com/19242849/39942554-cde97ae8-552d-11e8-87e7-07394e4a8391.png">

Am I missing something obvious?

**Comment by jbednar** [comment]
I might have forgotten some obscure corner of the code, but I don't think there is currently any option to invert the y axis in datashader.  I'd recommend using [HoloViews](http://holoviews.org) instead of InteractiveImage, because it offers an `invert_yaxis=True` option that should take care of this issue.

InteractiveImage will actually be deprecated in the next release; it's a very limited object that mainly served as an example, and it has now been supplanted by full datashader support in HoloViews.
