### ISSUE TITLE
How to plot the mean of several columns in the same plot?

### ISSUE THREAD

**Issue by joelostblom** [bokeh/datashader#71]
I have a data frame with four columns: `x-coordinates`, `y-coordinates`, `weight` and `height`. I want the data points to be colored according to their `weight` and `height` in two different colormaps, rather than by density.

This is my progress so far:

```python
import datashader as ds
from datashader import transfer_functions as tf
from functools import partial

def create_image(x_range, y_range, w, h, color_fn=tf.interpolate):
    cvs = ds.Canvas(plot_width=w, plot_height=h, x_range=x_range, y_range=y_range)
    agg = cvs.points(df, 'x-coord',  'y-coord',  ds.mean('weight'))
    image = color_fn(agg)
    return image

create_image(x_range, y_range, 400, 250, color_fn=partial(tf.interpolate, low="lightgrey", high='black', how='log'))
```

How would I go about adding the mean of `height` and plot it in a colorscale from `lightred` to `darkred`, so that the final plot displays both `height` and `weight` in two different color maps in the same plot. This would be similar to the census example in the webinar, where ethnicities were plotted in different colors (although that was according to the density rather than the mean values of another column).

**Comment by jcrist** [comment]
When you say "the final plot displays both height and weight in two different colormaps in the same plot", I'm not sure what you mean.

```python
agg = ds.Canvas().points(df, 'x-coord', 'y-coord', ds.summary(height=ds.mean('height'),
                                                              width=ds.mean('width')))
```

will collect the mean height and width values accumulated in each bin in the aggregate. The question then is how do you transform this aggregate meaningfully into an image. You can't just create two images and then stack them, as they'll 100% overlap. One could interpolate between their product, to get an image conveying total size magnitude, but I'm not sure if that's what you want:

```
img = tf.interpolate(agg.width * agg.height, 'lightred', 'darkred')
```

**Comment by jbednar** [comment]
In the census example, every datapoint had one associated race, and for each pixel in the plot we collected counts for each possible race.  Given those counts (essentially a histogram over the race field, per pixel), we then chose a particular color as an average of the colors for each race, weighted by the counts of that race.  Thus when looking at a single point, the color will be the race associated with that point, with two points it will be the average of the two colors for the races of those two pixels, etc.  I don't think this is comparable to the case that you outline, where each datapoint has two associated values, one for height and one for width -- here you are asking two combine multiple fields per point, whereas the census data combined multiple category values across points.  So I don't think the census example will help you achieve what you are after.

**Comment by jbednar** [comment]
If you are trying to plot what effectively is a multidimensional data space per datapoint (not a scalar per point, as in the census data, but more than one value per point) in the same plot, then you can use RGB images if you are careful.  RGB images are composed of three orthogonal color axes, one each for R, G, and B, and you can assign each of those to different fields in your data, such that areas with high height might end up with a high R value (reddish), high width might end up with a high G value (greenish), and those with both height and width high would end up with both R and G high (yellowish, since for RGB images, values with both R and G high are yellow).

To do this, I'd recommend using an explicit RGB representation for the colors, rather than color names, so that you are certain that you are only changing a single channel of the image at a time:

```python
height = tf.interpolate(agg.height, '#110000', '#FF0000')
width  = tf.interpolate(agg.width,  '#001100', '#00FF00')
depth  = tf.interpolate(agg.depth,  '#000011', '#0000FF')
img = tf.merge(height, width, depth)
```

Here `depth` shows what you would do if  you needed a third channel, where the result would be white if all three channels were high in value, but in your case you only need two of the three available channels, so you can just omit `depth`.

Note that `tf.merge` will average the channels, when what you really want is to sum all these together per pixel, so that a pixel made out of #AA0000 and #00BB00 yields #AABB00.  @jcrist, can we make merge() accept a parameter for the reduction method, so that a user can change `mean` to `sum` when appropriate, as in this case?  I also am not sure how to make the background start as black when there's no data, as would be appropriate in this case.

Again, I'm not sure if this is what the original question was about, but it is a valid way of plotting multidimensional data (up to three dimensions) in the same image without having the dimensions clobber each other.
