### ISSUE TITLE
Implement heatmap

### ISSUE THREAD

**Issue by apaytuvi** [bokeh/datashader#87]
Hello everybody,

I've seen many examples how to implement a heatmap with `bokeh`, but none about how doing it with `datashader`. I've already tested the taxi example and implemented my data, but it just shows a scatter plot, not a heatmap.

I think I should change something in and around this line:
`pix = tf.interpolate(agg, low='lightblue', high='red', how=self.model.transfer_function)`

However, I do not know how to proceed. What I would like is something like [this](http://bokeh.pydata.org/en/0.8.1/docs/user_guide/charts.html#heatmap). Is it possible with `datashader`? Is it possible, as well, that I click into a point and displays the information in that point?

**Comment by jbednar** [comment]
The NYC Taxi example *is* a heatmap, not a scatterplot.  By default, it's at a high resolution (approximately one bin per screen pixel), which will look like a scatterplot when you zoom in enough, but really it's a heatmap, i.e., a 2D histogram with pixel colors determined by the counts in each bin.  Just reduce the plot height and width if you want to have coarser bins so that you can see the bin boundaries.

As for clicking into a point and displaying the information in that point, we are working on a good API to provide that information from datashader so that e.g. Bokeh can show it when the mouse hovers over a certain bin.  However, we still have a good ways to go before making that functionality available.

**Comment by jbednar** [comment]
See issue #91 for tracking progress on hover support.
